### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by shakeyourbunny** [ThePBone/CrunchyrollDownloader#1]
Hello,

I tested the downloader and have found some (showstopper) bugs and have some suggestions. My platform is Windows 8.1 Professional.

- there is no obvious documentation, if I didn't try "--help" out, I would not have found the command line options

- --terminal does nothing in Windows (what it is supposed to do?)
- --query <string> does nothing, just launches the GUI
- --terminal --query <string> does nothing to

- on clicking on  the "change" button of the series panel and entering something eg "Squid Girl" does list the series, but the dialog window is non-resizeable and there no buttons for confirming the selected series. I guess this is on the right side of the list box, but this is not visible nor it is resizable ....so I cannot do anything further. 

How do I confirm the selection with the keyboard? "Enter" doesnt do anything, nor the space key.

Please fix.

**Comment by ThePBone** [comment]
Hey, thanks for your report!
I will update the readme and add information about the command-line mode soon.

At the moment there is no such argument as `--terminal`, please use `-t` instead. Apparently it is listed when running `--help`, so it looks like I forgot to set up a trigger for `--terminal`.

However, your second issue is a bit strange. The dialog should be resizable and update its layout automatically when the frame is resized.
[(How it should look)](https://i.imgur.com/upaG1OH.gif)
After selecting a series in the dialog, you can also hit Tab to set focus on the OK button and then hit Enter to accept

**Comment by shakeyourbunny** [comment]
I dunno, but under Windows 8.1 the dialog window is not resizable and the buttons aren't visible. Perhaps the layout container is not a percentage of the dialog windows, but a fixed pixel size?

See https://i.imgur.com/VGHsOJP.gif for a demonstration.

**Comment by shakeyourbunny** [comment]
The episode selection dialog is similar broken and non-resizeable... 
https://i.imgur.com/qV029AU.gif

and obviously the downoader does something, but there are no episodes after the application has 
finished all downloads.
https://i.imgur.com/iIAjKKw.gif

**Comment by ThePBone** [comment]
I don't know what causes these strange dialog layouts, it might be a win8-only issue with Qt.

I'm aware of the other bug though, the downloader would skip all episodes with special chars in the episode names, because some generated filenames were invalid (only on ntfs drives).
There's a patch for that issue available [here](https://github.com/ThePBone/CrunchyrollDownloader/releases/tag/1.1)

**Comment by shakeyourbunny** [comment]
Dunno, but this was really the first application where I encountered this, I also use other QT-based application which have no issues on resizing or similar stuff. 

I already downloaded the revised version, but sadly no fix on the dialog issues. It is also weird that there are no control buttons in the window frame, I guess there are none set.

**Comment by ThePBone** [comment]
Tbh, I'm pretty clueless on this issue. But there are a few workarounds that could work.
You could run the app in unaware DPI mode, open a command line window in the directory of the CrunchyrollDownloader and run these commands:
```
set QT_AUTO_SCREEN_SCALE_FACTOR=1
CrunchyrollDownloader.exe
```
 I can't guarantee that this will help though.

**Comment by shakeyourbunny** [comment]
Thank you for your reply, but I think this does not have something to do with DPI settings, rather that the dialog boxes are created (WM_CREATE) without the necessary flags for the standard user interface elements one expects.. like Minimize/Maximize/Close/Resize.

Nothing against you, but there seems to be a trend in creating non-modal screen-filling dialogboxes ("metro" aka Windows 10 Style) dialogs which really annoying.

**Comment by ThePBone** [comment]
Actually I didn't intend to have dialog boxes without titlebar buttons.
I'm doing most of the testing on Linux, that's why I didn't notice this behaviour on Windows machines.
But I published a small update [here](https://github.com/ThePBone/CrunchyrollDownloader/releases/tag/1.2.1), it adds the missing titlebar buttons and it might even fix your scaling issues.
