### ISSUE TITLE
Can't install the dependencies on Ubuntu 18.04

### ISSUE THREAD

**Issue by Gregory280** [ThePBone/CrunchyrollDownloader#10]
it returns it was impossible to find the package qtbase5-devlibqt5widgets5"

sudo apt install qt5-qmake qtbase5-devlibqt5widgets5 libqt5gui5 libqt5core5a libqt5xml5

**Comment by ThePBone** [comment]
Oh. That's a typo in the readme, use this instead: 
```
sudo apt install qt5-qmake qtbase5-devlibqt5widgets5 libqt5gui5 libqt5core5a libqt5xml5 
```
