### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by Vangelis27** [ThePBone/CrunchyrollDownloader#13]
This is the error i am getting: "An error has occurred the server encountered an unexpected condition which prevented it from fulfilling the request." It first happend a couple days ago. After pressing OK, trying to search anything it prints a new error: "An error occurred: Unauthenticated request (bad_session)".

![Annotation 2020-04-16 192734](https://user-images.githubusercontent.com/11654086/79481581-6200a000-8018-11ea-8748-70ace47d7d24.jpg)

![Annotation 2020-04-16 193047](https://user-images.githubusercontent.com/11654086/79481940-d0456280-8018-11ea-8adf-e32686893bed.jpg)

**Comment by ThePBone** [comment]
Thanks for reporting this issue. Crunchyroll has changed their private token for accessing their API. I've already updated the token in the code (commit: 52fde1fc5f65afab91911fc9bb1afe2dbcce1b7a) over a month ago but I hadn't the time to compile and release a new binary version for Windows.
I'll try to get one online soon.

**Comment by ThePBone** [comment]
Update is released and tested, everything should work as expected now.
<https://github.com/ThePBone/CrunchyrollDownloader/releases/tag/1.2.2>
