### ISSUE TITLE
Separated Subtitles

### ISSUE THREAD

**Issue by werewolf004** [ThePBone/CrunchyrollDownloader#15]
Hi,
Is there a way to get subtitle separated from the MP4 files (video + audio + ass files in mp4 contenair) ? I search but don't find the way to do it.
Thanks

**Comment by ThePBone** [comment]
Unfortunately no. I'm using the same Crunchyroll API interface used by Crunchyroll's Android App to fetch video streams from their servers. But that API (and the actual android app) only support burned-in subs.
