### ISSUE TITLE
ByPass Geoblock (US Proxy) doesn't work

### ISSUE THREAD

**Issue by werewolf004** [ThePBone/CrunchyrollDownloader#16]
It seems the bypass geoblock via US Proxy doesn't work anymore, I try to connect to get some US anime protected by country localisation but when I'm loggin it say there is an error (look picture below). If I remove the bypass proxy, it work fine.
Used version => last available
![2020-05-03 12_44_57-Windows 7 x64 - VMware Workstation](https://user-images.githubusercontent.com/63142830/80912247-f7e83a80-8d3b-11ea-9c9d-f331453e5d07.png)

**Comment by ThePBone** [comment]
I just tested it and it worked fine for me. But I've also noticed that the proxy has returned error messages every now and then over the past month.

I'm using <https://api1.cr-unblocker.com/getsession.php?version=1.1> to get an US session id, but their servers seem to have a few issues lately.
The maintainer of that unblocker proxy also said on their [website](https://cr-unblocker.com/) they stopped working on their unblocker project, so these server issues on their side are unlikely to be fixed anytime soon (maybe they'll take down their servers altogether). 

Alternatively, I could host my own unblocker server, but I don't have a server in the United States and not enough resources to host it permanently anyway.

But if it still doesn't work you can use this workaround using a VPN:
```
The geoblock bypass might not work as expected since
the third-party proxy server (cr-unblocker.com) is experiencing issues.
As a workaround, you can enable a US VPN while logging in.
As soon as you were assigned an american session id you can disable your VPN
and use your real network connection to download content.
```
