### ISSUE TITLE
GUI scaling issues

### ISSUE THREAD

**Issue by Vangelis27** [ThePBone/CrunchyrollDownloader#18]
i have a 1366x760 monitor and this happens

[Screen Recording.zip](https://github.com/ThePBone/CrunchyrollDownloader/files/4672106/Screen.Recording.zip)

i added the video on a zip file since github doesn't support mp4 files.

**Comment by ThePBone** [comment]
Oops, I forgot about those monitors 😅. I think I could put the whole GUI into a scrollable container to fix that issue.

**Comment by ThePBone** [comment]
88aa1fd171dc09047409149360de323a0e90f28e fixes your issue.
You can download the latest nightly build for Windows here: 
<https://ci.appveyor.com/api/buildjobs/m6nr9bjx3v4fjs3f/artifacts/crdownloader-win64_1.2.30.zip>
