### ISSUE TITLE
premium not working. 

### ISSUE THREAD

**Issue by TheJulkka** [ThePBone/CrunchyrollDownloader#2]
so i have premium through vrv.
 so i think that might be the issue but i have no clue how to fix it. 
![crunchyroll downloaderSieppaa](https://user-images.githubusercontent.com/58823817/70734560-24f86a00-1d15-11ea-9403-ddfd5088522e.PNG)

**Comment by ThePBone** [comment]
That's most likely the issue. What happens if you try to download Premium-only videos? Does it display these videos as unavailable or does it download them anyways?

**Comment by ThePBone** [comment]
Closed, because there were no updates since quite some time and VRV is a bit out of scope (for now).

Feel free to reopen.
