### ISSUE TITLE
Ability to download videos without subtitles

### ISSUE THREAD

**Issue by jktoiuhito** [ThePBone/CrunchyrollDownloader#3]
Some of Crunchyroll's videos have subtitle-less versions. I think these should be able to be downloaded as well.

**Comment by ThePBone** [comment]
While this feature would be cool, this is not possible with the API interface I am using. It is the same one as the android app uses, but it only provides HLS streams of videos with burned-in subs. 
I'll look into it though, maybe I can find a workaround

**Comment by jktoiuhito** [comment]
Ok. It might be better then to request Crunchyroll to add this feature to their apps - and therefore API - first. I'd assume that adding code for scraping the web page just for this one feature would be quite a humongous amount of work for relatively little gain.

**Comment by ThePBone** [comment]
Yeah, if Crunchyroll would add this feature to their android app, it would be optimal. I don't have plans to switch to their API used by the website at the moment, but maybe that will be implemented it as an alternative in future.
