### ISSUE TITLE
Premium not working with an official CR premium account (not through vrv)

### ISSUE THREAD

**Issue by mileyvirus** [ThePBone/CrunchyrollDownloader#4]
![CrunchyrollDownloader 2019-12-28 at 22 57 58@2x](https://user-images.githubusercontent.com/7974896/71549894-90a12f00-29c5-11ea-98ed-10b9cfa1e2e5.png)

**Comment by mileyvirus** [comment]
By the way I compiled for macOS if you want the build for the releases!

**Comment by ThePBone** [comment]
What happens after you press 'Update session'? Does it just do nothing or does the session status update?

**Comment by mileyvirus** [comment]
It now works, I'm unsure if the issue was fixed because:

- I had to create a username on Crunchyroll's website.
- Because you did something in aada8d6

¯\_(ツ)_/¯
