### ISSUE TITLE
Wont find some region locked animes even with geoblock bypass ON

### ISSUE THREAD

**Issue by TaigaChiquita** [ThePBone/CrunchyrollDownloader#8]
as the title says i'm not able to find any anime that is region blocked, at first i thought it could be that they were only premium animes so i logged in with my premium account and nothing changed 
BTW the Downloader does recognize that my account is premium.
so i startes searching for more region locked animes and none of them appear in the Downloader search window.
I'm from Chile and i was trying to download Fire Force and Kakuriyo no Yadomesh but as i said, i couldn't find them

**Comment by ThePBone** [comment]
I'm using an API of an unblocking provider (cr-unblocker.com) to bypass geoblock, so it is very likely that this issue occurred on their side. I noticed that their API seemed to be a bit unstable lately so here is an easy workaround for now:

*As a workaround, you can enable a US VPN **while logging in.**
As soon as you were assigned an american session id you can disable your VPN and use your real network connection to download content.*
